### ISSUE TITLE
Immediate 180 degree changes of direction cause death

### ISSUE THREAD

**Issue by FridayPush** [TowhidKashem/snake-game#1]
When executing a 180 degree turn in quick succession results in the game over screen instead of turning correctly. I suspect validation that an additional movement 'step' has occurred is necessary to correct. 

For example: 
```
Snake moving right ====>
GAME LOGIC STEP
KeyboardEvent dispatched with 'UP'
UpdateDirection to UP
KeyboardEvent dispatched with 'LEFT'
Update Direction to LEFT
GAME LOGIC STEP
Snake Head moves 1 frame left... hits self. 
```

**Comment by gregolai** [comment]
Need to create an intermediate variable that the next direction gets assigned to, then on the next update frame, copy that into this.game.direction.

**Comment by TowhidKashem** [comment]
Thanks again for reporting, I committed [the fix](https://github.com/TowhidKashem/snake-game/commit/ac008dd0616fe0a56b6831d4eb23af82417d8549) directly to the master branch (didn't want to bother with formal PR process atm). After the change I can't replicate the bug anymore, let me know if you still see it otherwise I'll close the issue. Best!

**Comment by FridayPush** [comment]
Thanks for looking into the feedback. The described fix works but it also introduces a new problem, that you're essentially discarding user key presses, and their intention, if they perform their actions too fast for the current game loop. It's easiest to see the remaining issue on the 'easy' setting. If you attempt to perform a 180 degree turn by rolling your key presses at nearly the same moment the snake will ignore the second key press. 

```
Snake headed right 
Game Logic Step
KeyboardEvent UP
NextDirection Up
KeyboardEvent Left
Game Logic Step
Snake headed up 
NextDirection cleared
Game Logic Step
Snake headed up 
```

An alternative would be to implement an event queue, I found a good description along with why this would be an [issue in a fighting game here](https://shivansite.wordpress.com/2013/11/13/using-a-queue-for-user-input-events/). 

For example trying to throw a fireball in Streetfighter would be a good problem case. The expected player input is to roll the joystick from left, left/down, down, down/right, right and then press A. If a part of that sequence is delivered inside the same game logic step the fireball sequence would fail to be recognized.  

Feel free to close this, the death issue is fixed and on harder difficulties the logic steps are fast enough to not trigger the condition.

**Comment by TowhidKashem** [comment]
@FridayPush You know I actually had a suspicion I might have been throwing away key presses when I made that change, but you have to hit the keys so fast it's really hard to test. I think if I really slow the game speed down I should be able to see the problem though. Very cool concept about the event queue, this is my first game so I never really encountered these sorts of problems before.

I'll close the issue for now since it's an edge case and I don't have the time to delve deeper into this atm but I'll read that article you linked when I have time, it seems real interesting. Thanks again!
